#!/bin/bash

INSTALL=0
YES_OPTION=""
COMPILE_OPTION=""
EMPIRE_ARGS=()

for arg in "$@"; do
  case $arg in
    install)
      INSTALL=1
      ;;
    -y)
      YES_OPTION="-y"
      ;;
    -c)
      COMPILE_OPTION="-c"
      ;;
    *)
      EMPIRE_ARGS+=("$arg")
      ;;
  esac
done

if [ $INSTALL -eq 1 ]; then
  ./setup/install.sh $YES_OPTION $COMPILE_OPTION
fi

sudo -E poetry run python empire.py "${EMPIRE_ARGS[@]}"