"""agent_files.session_id: widen to String(255) and add FK to agents

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-25

Widen agent_files.session_id from String(50) to String(255) to match
agents.session_id, and add a FK with ondelete=CASCADE so agent deletion
cascades to owned files — consistent with the agent_tasks / agent_checkins
pattern.

Idempotent: orphan rows are removed before the constraint is added; FK
creation is skipped when the constraint already exists (i.e., fresh installs
where create_all() built the table from the updated model).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = inspect(bind)

    # Remove rows whose session_id references a non-existent agent so the FK
    # constraint can be added cleanly. Rows with NULL session_id are left
    # intact (NULL is a valid FK value meaning "no agent").
    op.execute(
        sa.text(
            "DELETE FROM agent_files"
            " WHERE session_id IS NOT NULL"
            " AND session_id NOT IN (SELECT session_id FROM agents)"
        )
    )

    # Detect whether the FK already exists (fresh installs where create_all()
    # built the table with the updated model — we must not add it twice).
    existing_fks = insp.get_foreign_keys("agent_files")
    has_session_id_fk = any(
        fk.get("referred_table") == "agents"
        and "session_id" in fk.get("constrained_columns", [])
        for fk in existing_fks
    )

    with op.batch_alter_table("agent_files", schema=None) as batch_op:
        batch_op.alter_column(
            "session_id",
            existing_type=sa.String(50),
            type_=sa.String(255),
            existing_nullable=True,
        )
        if not has_session_id_fk:
            batch_op.create_foreign_key(
                "fk_agent_files_session_id",
                "agents",
                ["session_id"],
                ["session_id"],
                ondelete="CASCADE",
            )


def downgrade() -> None:
    bind = op.get_bind()
    insp = inspect(bind)

    # Collect FKs from agent_files.session_id → agents. MySQL assigns an
    # explicit name (auto-generated by create_all or "fk_agent_files_session_id"
    # from upgrade); SQLite leaves the FK anonymous (name=None). We map unnamed
    # FKs to their naming-convention derivation so batch_alter_table can target
    # them via drop_constraint.
    existing_fks = insp.get_foreign_keys("agent_files")
    fk_names_to_drop = [
        fk.get("name") or "fk_agent_files_session_id"
        for fk in existing_fks
        if fk.get("referred_table") == "agents"
        and "session_id" in fk.get("constrained_columns", [])
    ]

    # naming_convention lets batch_alter_table assign the derived name
    # "fk_agent_files_session_id" to SQLite's anonymous FK so drop_constraint
    # can target it. On MySQL the FK has an explicit name and is targeted
    # directly; the convention is a no-op for already-named constraints.
    with op.batch_alter_table(
        "agent_files",
        schema=None,
        naming_convention={"fk": "fk_%(table_name)s_%(column_0_name)s"},
    ) as batch_op:
        for name in fk_names_to_drop:
            batch_op.drop_constraint(name, type_="foreignkey")
        batch_op.alter_column(
            "session_id",
            existing_type=sa.String(255),
            type_=sa.String(50),
            existing_nullable=True,
        )
